In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])  # não consegue armazenar arquivos de tipo de dado diferente
print(x)

[1 2 3]


In [3]:
y = [1,2,3]

In [4]:
print(x + y)

[2 4 6]


In [6]:
z = np.zeros((5))
print(z)

[0. 0. 0. 0. 0.]


In [7]:
ones = np.ones((5))
print(ones)

[1. 1. 1. 1. 1.]


In [14]:
# array bidemensional

x = np.array([[2,3,4], [3,4,5]])
print(x)
x[0][2]

[[2 3 4]
 [3 4 5]]


4

In [17]:
y = np.array([[1,2,3]]*3)
print(y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
z = np.zeros((3, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
x = np.arange(10,25,2)
x

array([10, 12, 14, 16, 18, 20, 22, 24])

In [29]:
x = np.array([[1,2,3]]*5)
print(x)
y = np.array([[2,3,4]]*5)
print(y)

x+y # somando matrizes

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]]


array([[3, 5, 7],
       [3, 5, 7],
       [3, 5, 7],
       [3, 5, 7],
       [3, 5, 7]])

In [30]:
x = np.array([[1,2,3]]*5)
print(x)
y = np.array([[2,3,4]]*5)
print(y)

x*y # multiplicando matrizes

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]
 [2 3 4]]


array([[ 2,  6, 12],
       [ 2,  6, 12],
       [ 2,  6, 12],
       [ 2,  6, 12],
       [ 2,  6, 12]])